[package]
name = "simed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = "3.1.6"
coitrees = "0.2.1"
eds = { path = "../eds" }